/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { JudgmentRecord } from '../models/citationTypes.ts';

/**
 * Comprehensive master catalog of landmark Indian Supreme Court and High Court judgments.
 * Covers foundational constitutional, criminal, civil, arbitration, IP, environmental,
 * and service jurisprudence from 1950 through 2025.
 */
export const LANDMARK_JUDGMENTS_DATABASE: JudgmentRecord[] = [
  // 1. Kesavananda Bharati
  {
    caseId: 'SC-1973-13364',
    caseName: 'Kesavananda Bharati Sripadagalvaru v. State of Kerala',
    petitioner: 'His Holiness Kesavananda Bharati Sripadagalvaru',
    respondent: 'State of Kerala and Another',
    court: 'Supreme Court of India',
    decisionDate: '1973-04-24',
    year: 1973,
    citations: ['(1973) 4 SCC 225', 'AIR 1973 SC 1461', '[1973] 4 SCR 541', '1973 INSC 120'],
    normalizedCitations: [],
    docketNumber: 'Writ Petition (Civil) No. 135 of 1970',
    bench: ['S.M. Sikri, C.J.I.', 'J.M. Shelat, J.', 'H.R. Khanna, J.', 'Y.V. Chandrachud, J.'],
    docType: 'judgment',
    sourceUrl: 'https://main.sci.gov.in/judgment/judis/13364.pdf',
    isOfficialSource: true,
    chunks: [
      {
        chunkIndex: 0,
        totalChunks: 1,
        text: 'The power of Parliament to amend the Constitution under Article 368 does not extend to altering or destroying the basic structure or essential framework of the Constitution.',
        heading: 'Basic Structure Doctrine Formulation',
        sourceUrl: 'https://main.sci.gov.in/judgment/judis/13364.pdf',
      },
    ],
    keyPassages: ['Parliament cannot amend the basic structure or fundamental framework of the Constitution under Article 368.'],
    headnotes: 'Constitutional Law - Article 368 - Scope of Constituent Amending Power - Doctrine of Basic Structure articulated.',
  },

  // 2. Maneka Gandhi
  {
    caseId: 'SC-1978-5581',
    caseName: 'Maneka Gandhi v. Union of India',
    petitioner: 'Maneka Gandhi',
    respondent: 'Union of India and Another',
    court: 'Supreme Court of India',
    decisionDate: '1978-01-25',
    year: 1978,
    citations: ['(1978) 1 SCC 248', 'AIR 1978 SC 597', '[1978] 2 SCR 621', '1978 INSC 16'],
    normalizedCitations: [],
    docketNumber: 'Writ Petition (Civil) No. 231 of 1977',
    bench: ['M.H. Beg, C.J.I.', 'Y.V. Chandrachud, J.', 'P.N. Bhagwati, J.', 'V.R. Krishna Iyer, J.'],
    docType: 'judgment',
    sourceUrl: 'https://main.sci.gov.in/judgment/judis/5581.pdf',
    isOfficialSource: true,
    chunks: [
      {
        chunkIndex: 0,
        totalChunks: 1,
        text: 'The procedure established by law under Article 21 cannot be arbitrary, oppressive, or fanciful; it must be just, fair, and reasonable in nature.',
        heading: 'Procedure Established by Law',
        sourceUrl: 'https://main.sci.gov.in/judgment/judis/5581.pdf',
      },
    ],
    keyPassages: ['Procedure established by law under Article 21 must satisfy the tests of reasonableness, fairness, and non-arbitrariness.'],
    headnotes: 'Constitution of India - Article 21 - Personal Liberty - Right to Travel Abroad - Principles of Natural Justice.',
  },

  // 3. Justice K.S. Puttaswamy (Privacy)
  {
    caseId: 'SC-2017-36735',
    caseName: 'Justice K.S. Puttaswamy (Retd.) v. Union of India',
    petitioner: 'Justice K.S. Puttaswamy (Retd.) and Another',
    respondent: 'Union of India and Others',
    court: 'Supreme Court of India',
    decisionDate: '2017-08-24',
    year: 2017,
    citations: ['(2017) 10 SCC 1', 'AIR 2017 SC 4161', '2017 INSC 752'],
    normalizedCitations: [],
    docketNumber: 'Writ Petition (Civil) No. 494 of 2012',
    bench: ['J.S. Khehar, C.J.I.', 'J. Chelameswar, J.', 'S.A. Bobde, J.', 'D.Y. Chandrachud, J.'],
    docType: 'judgment',
    sourceUrl: 'https://main.sci.gov.in/supremecourt/2012/36735/36735_2012_Judgement_24-Aug-2017.pdf',
    isOfficialSource: true,
    chunks: [
      {
        chunkIndex: 0,
        totalChunks: 1,
        text: 'The right to privacy is protected as an intrinsic part of the right to life and personal liberty under Article 21 and as a part of the freedoms guaranteed by Part III of the Constitution.',
        heading: 'Fundamental Right to Privacy Declared',
        sourceUrl: 'https://main.sci.gov.in/supremecourt/2012/36735/36735_2012_Judgement_24-Aug-2017.pdf',
      },
    ],
    keyPassages: ['The right to privacy is a fundamental right under Article 21 of the Constitution of India.'],
    headnotes: 'Constitutional Law - Article 21 - Fundamental Right to Privacy - Overruling of M.P. Sharma and Kharak Singh.',
  },

  // 4. Shreya Singhal
  {
    caseId: 'SC-2015-42497',
    caseName: 'Shreya Singhal v. Union of India',
    petitioner: 'Shreya Singhal',
    respondent: 'Union of India',
    court: 'Supreme Court of India',
    decisionDate: '2015-03-24',
    year: 2015,
    citations: ['(2015) 5 SCC 1', 'AIR 2015 SC 1523', '2015 INSC 240'],
    normalizedCitations: [],
    docketNumber: 'Writ Petition (Criminal) No. 167 of 2012',
    bench: ['J. Chelameswar, J.', 'R.F. Nariman, J.'],
    docType: 'judgment',
    sourceUrl: 'https://main.sci.gov.in/judgment/judis/42497.pdf',
    isOfficialSource: true,
    chunks: [
      {
        chunkIndex: 0,
        totalChunks: 1,
        text: 'Section 66A of the Information Technology Act, 2000 is struck down in its entirety being violative of Article 19(1)(a) and not saved under Article 19(2).',
        heading: 'Invalidation of Section 66A IT Act',
        sourceUrl: 'https://main.sci.gov.in/judgment/judis/42497.pdf',
      },
    ],
    keyPassages: ['Section 66A of the Information Technology Act is unconstitutional and struck down.'],
    headnotes: 'Information Technology Act, 2000 - Section 66A - Freedom of Speech and Expression - Void for Vagueness and Overbreadth.',
  },

  // 5. Navtej Singh Johar
  {
    caseId: 'SC-2018-45001',
    caseName: 'Navtej Singh Johar v. Union of India',
    petitioner: 'Navtej Singh Johar and Others',
    respondent: 'Union of India through Ministry of Law and Justice',
    court: 'Supreme Court of India',
    decisionDate: '2018-09-06',
    year: 2018,
    citations: ['(2018) 10 SCC 1', 'AIR 2018 SC 4321', '2018 INSC 790'],
    normalizedCitations: [],
    docketNumber: 'Writ Petition (Criminal) No. 76 of 2016',
    bench: ['Dipak Misra, C.J.I.', 'A.M. Khanwilkar, J.', 'D.Y. Chandrachud, J.', 'R.F. Nariman, J.', 'Indu Malhotra, J.'],
    docType: 'judgment',
    sourceUrl: 'https://main.sci.gov.in/supremecourt/2016/14961/14961_2016_Judgement_06-Sep-2018.pdf',
    isOfficialSource: true,
    chunks: [
      {
        chunkIndex: 0,
        totalChunks: 1,
        text: 'Section 377 of the Indian Penal Code, insofar as it criminalises consensual sexual conduct between adults of the same sex, is unconstitutional and violative of Articles 14, 15, 19 and 21.',
        heading: 'Decriminalisation of Section 377 IPC',
        sourceUrl: 'https://main.sci.gov.in/supremecourt/2016/14961/14961_2016_Judgement_06-Sep-2018.pdf',
      },
    ],
    keyPassages: ['Consensual sexual acts of adults in private are decriminalised; Suresh Koushal overruled.'],
    headnotes: 'Indian Penal Code - Section 377 - Constitutional Morality - Equality and Dignity of LGBTQ+ individuals.',
  },

  // 6. In Re: Noise Pollution
  {
    caseId: 'SC-2005-4100',
    caseName: 'In Re: Noise Pollution - Implementation of Laws for Restricting Use of Loudspeakers',
    petitioner: 'Forum, Prevention of Envn. and Sound Pollution',
    respondent: 'Union of India and Others',
    court: 'Supreme Court of India',
    decisionDate: '2005-07-18',
    year: 2005,
    citations: ['(2005) 5 SCC 733', 'AIR 2005 SC 3136', '2005 INSC 321'],
    normalizedCitations: [],
    docketNumber: 'Writ Petition (Civil) No. 72 of 1998',
    bench: ['R.C. Lahoti, C.J.I.', 'Ashok Bhan, J.'],
    docType: 'judgment',
    sourceUrl: 'https://main.sci.gov.in/judgment/judis/27045.pdf',
    isOfficialSource: true,
    chunks: [
      {
        chunkIndex: 0,
        totalChunks: 1,
        text: 'Freedom from noise pollution is a facet of the right to life guaranteed under Article 21. No one can claim a fundamental right to create noise creating nuisance to others.',
        heading: 'Noise Pollution and Article 21',
        sourceUrl: 'https://main.sci.gov.in/judgment/judis/27045.pdf',
      },
    ],
    keyPassages: ['Noise pollution violates the right to life under Article 21 of the Constitution.'],
    headnotes: 'Environment Protection - Noise Pollution (Regulation and Control) Rules, 2000 - Article 21 Right to peaceful sleep.',
  },

  // 7. I.C. Golak Nath v. State of Punjab
  {
    caseId: 'SC-1967-124',
    caseName: 'I.C. Golak Nath v. State of Punjab',
    petitioner: 'I.C. Golak Nath and Others',
    respondent: 'State of Punjab and Another',
    court: 'Supreme Court of India',
    decisionDate: '1967-02-27',
    year: 1967,
    citations: ['AIR 1967 SC 1643', '[1967] 2 SCR 762', '1967 INSC 45'],
    normalizedCitations: [],
    docketNumber: 'Writ Petition No. 153 of 1965',
    bench: ['K. Subba Rao, C.J.I.', 'K.N. Wanchoo, J.', 'M. Hidayatullah, J.', 'J.C. Shah, J.', 'S.M. Sikri, J.'],
    docType: 'judgment',
    sourceUrl: 'https://main.sci.gov.in/judgment/judis/3775.pdf',
    isOfficialSource: true,
    chunks: [
      {
        chunkIndex: 0,
        totalChunks: 1,
        text: 'Parliament has no power from the date of this decision to amend any of the provisions of Part III of the Constitution so as to take away or abridge the fundamental rights enshrined therein.',
        heading: 'Prospective Overruling Doctrine',
        sourceUrl: 'https://main.sci.gov.in/judgment/judis/3775.pdf',
      },
    ],
    keyPassages: ['Fundamental rights are given a transcendental position and cannot be abridged by amendment under Article 368.'],
    headnotes: 'Constitution of India - Article 368 and Article 13(2) - Fundamental Rights Amending Power - Doctrine of Prospective Overruling.',
  },

  // 8. Minerva Mills Ltd. v. Union of India
  {
    caseId: 'SC-1980-356',
    caseName: 'Minerva Mills Ltd. v. Union of India',
    petitioner: 'Minerva Mills Ltd. and Others',
    respondent: 'Union of India and Others',
    court: 'Supreme Court of India',
    decisionDate: '1980-07-31',
    year: 1980,
    citations: ['(1980) 3 SCC 625', 'AIR 1980 SC 1789', '[1981] 1 SCR 206', '1980 INSC 141'],
    normalizedCitations: [],
    docketNumber: 'Writ Petition No. 356 of 1977',
    bench: ['Y.V. Chandrachud, C.J.I.', 'P.N. Bhagwati, J.', 'V.R. Krishna Iyer, J.', 'N.L. Untwalia, J.', 'P.S. Kailasam, J.'],
    docType: 'judgment',
    sourceUrl: 'https://main.sci.gov.in/judgment/judis/5412.pdf',
    isOfficialSource: true,
    chunks: [
      {
        chunkIndex: 0,
        totalChunks: 1,
        text: 'The Indian Constitution is founded on the bedrock of the balance between Parts III and IV. To give absolute primacy to one over the other is to disturb the harmony of the Constitution.',
        heading: 'Harmony between Fundamental Rights and Directive Principles',
        sourceUrl: 'https://main.sci.gov.in/judgment/judis/5412.pdf',
      },
    ],
    keyPassages: ['The limited amending power of Parliament is itself a basic feature of the Constitution.'],
    headnotes: 'Constitution (Forty-second Amendment) Act, 1976 - Clauses (4) and (5) of Article 368 unconstitutional.',
  },

  // 9. Indira Nehru Gandhi v. Raj Narain
  {
    caseId: 'SC-1975-450',
    caseName: 'Indira Nehru Gandhi v. Raj Narain',
    petitioner: 'Indira Nehru Gandhi',
    respondent: 'Raj Narain and Others',
    court: 'Supreme Court of India',
    decisionDate: '1975-11-07',
    year: 1975,
    citations: ['1975 Supp SCC 1', 'AIR 1975 SC 2299', '[1976] 2 SCR 347', '1975 INSC 253'],
    normalizedCitations: [],
    docketNumber: 'Civil Appeal No. 887 of 1975',
    bench: ['A.N. Ray, C.J.I.', 'H.R. Khanna, J.', 'K.K. Mathew, J.', 'M.H. Beg, J.', 'Y.V. Chandrachud, J.'],
    docType: 'judgment',
    sourceUrl: 'https://main.sci.gov.in/judgment/judis/4921.pdf',
    isOfficialSource: true,
    chunks: [
      {
        chunkIndex: 0,
        totalChunks: 1,
        text: 'Democracy, rule of law, equality of status and opportunity, and the jurisdiction of courts to adjudicate election disputes are essential features of the basic structure.',
        heading: 'Application of Basic Structure to Election Disputes',
        sourceUrl: 'https://main.sci.gov.in/judgment/judis/4921.pdf',
      },
    ],
    keyPassages: ['Article 329A(4) struck down as violative of the basic structure.'],
    headnotes: 'Constitution (Thirty-ninth Amendment) Act, 1975 - Judicial Review of Prime Minister Election - Basic Structure.',
  },

  // 10. A.K. Gopalan v. State of Madras
  {
    caseId: 'SC-1950-1',
    caseName: 'A.K. Gopalan v. State of Madras',
    petitioner: 'A.K. Gopalan',
    respondent: 'State of Madras',
    court: 'Supreme Court of India',
    decisionDate: '1950-05-19',
    year: 1950,
    citations: ['AIR 1950 SC 27', '[1950] SCR 88', '1950 INSC 14'],
    normalizedCitations: [],
    docketNumber: 'Petition No. 13 of 1950',
    bench: ['H.J. Kania, C.J.I.', 'Saiyid Fazl Ali, J.', 'M. Patanjali Sastri, J.', 'Mehr Chand Mahajan, J.', 'B.K. Mukherjea, J.', 'S.R. Das, J.'],
    docType: 'judgment',
    sourceUrl: 'https://main.sci.gov.in/judgment/judis/1.pdf',
    isOfficialSource: true,
    chunks: [
      {
        chunkIndex: 0,
        totalChunks: 1,
        text: 'Article 21 affords protection only against executive action not supported by law, not against legislative action.',
        heading: 'Early Literal Interpretation of Article 21',
        sourceUrl: 'https://main.sci.gov.in/judgment/judis/1.pdf',
      },
    ],
    keyPassages: ['Procedure established by law means procedure enacted by law of the State (subsequently expanded in Maneka Gandhi).'],
    headnotes: 'Preventive Detention Act, 1950 - Article 19 and Article 21 Mutual Exclusivity Doctrine (Overruled).',
  },

  // 11. S.R. Bommai v. Union of India
  {
    caseId: 'SC-1994-460',
    caseName: 'S.R. Bommai v. Union of India',
    petitioner: 'S.R. Bommai and Others',
    respondent: 'Union of India and Others',
    court: 'Supreme Court of India',
    decisionDate: '1994-03-11',
    year: 1994,
    citations: ['(1994) 3 SCC 1', 'AIR 1994 SC 1918', '[1994] 2 SCR 644', '1994 INSC 150'],
    normalizedCitations: [],
    docketNumber: 'Civil Appeal No. 3645 of 1989',
    bench: ['A.M. Ahmadi, J.', 'J.S. Verma, J.', 'P.B. Sawant, J.', 'K. Ramaswamy, J.', 'S.C. Agrawal, J.', 'Yogeshwar Dayal, J.', 'B.P. Jeevan Reddy, J.'],
    docType: 'judgment',
    sourceUrl: 'https://main.sci.gov.in/judgment/judis/10200.pdf',
    isOfficialSource: true,
    chunks: [
      {
        chunkIndex: 0,
        totalChunks: 1,
        text: 'Secularism and federalism are basic features of the Constitution. A proclamation issued under Article 356 is subject to judicial review.',
        heading: 'Article 356 Scope and Judicial Review',
        sourceUrl: 'https://main.sci.gov.in/judgment/judis/10200.pdf',
      },
    ],
    keyPassages: ['Secularism is a basic feature of the Constitution; Presidential proclamation under Article 356 is justiciable.'],
    headnotes: 'Constitution of India - Article 356 - Proclamation of President Rule - Judicial Review and Floor Test mandatory.',
  },

  // 12. Vishaka v. State of Rajasthan
  {
    caseId: 'SC-1997-789',
    caseName: 'Vishaka v. State of Rajasthan',
    petitioner: 'Vishaka and Others',
    respondent: 'State of Rajasthan and Others',
    court: 'Supreme Court of India',
    decisionDate: '1997-08-13',
    year: 1997,
    citations: ['(1997) 6 SCC 241', 'AIR 1997 SC 3011', '[1997] Supp 3 SCR 117', '1997 INSC 644'],
    normalizedCitations: [],
    docketNumber: 'Writ Petition (Criminal) Nos. 666-70 of 1992',
    bench: ['J.S. Verma, C.J.I.', 'Sujata V. Manohar, J.', 'B.N. Kirpal, J.'],
    docType: 'judgment',
    sourceUrl: 'https://main.sci.gov.in/judgment/judis/13824.pdf',
    isOfficialSource: true,
    chunks: [
      {
        chunkIndex: 0,
        totalChunks: 1,
        text: 'In the absence of enacted law to provide for effective enforcement of gender equality and personal dignity, guidelines and norms are laid down for workplace sexual harassment prevention.',
        heading: 'Vishaka Guidelines Formulated',
        sourceUrl: 'https://main.sci.gov.in/judgment/judis/13824.pdf',
      },
    ],
    keyPassages: ['Workplace sexual harassment violates Articles 14, 19(1)(g) and 21; Vishaka Guidelines formulated.'],
    headnotes: 'Sexual Harassment at Workplace - CEDAW Convention Incorporation - Guidelines until enactment of POSH Act.',
  },

  // 13. D.K. Basu v. State of West Bengal
  {
    caseId: 'SC-1997-101',
    caseName: 'D.K. Basu v. State of West Bengal',
    petitioner: 'D.K. Basu, Ashok K. Johri',
    respondent: 'State of West Bengal, State of U.P.',
    court: 'Supreme Court of India',
    decisionDate: '1996-12-18',
    year: 1997,
    citations: ['(1997) 1 SCC 416', 'AIR 1997 SC 610', '[1996] Supp 10 SCR 284', '1996 INSC 1599'],
    normalizedCitations: [],
    docketNumber: 'Writ Petition (Criminal) No. 592 of 1987',
    bench: ['Kuldip Singh, J.', 'A.S. Anand, J.'],
    docType: 'judgment',
    sourceUrl: 'https://main.sci.gov.in/judgment/judis/12690.pdf',
    isOfficialSource: true,
    chunks: [
      {
        chunkIndex: 0,
        totalChunks: 1,
        text: 'Custodial violence, including torture and death in the lock-ups, strikes a blow at the rule of law. Mandatory requirements for arrest and detention laid down.',
        heading: 'Guidelines on Arrest and Custodial Violence',
        sourceUrl: 'https://main.sci.gov.in/judgment/judis/12690.pdf',
      },
    ],
    keyPassages: ['Mandatory 11 guidelines to prevent custodial torture and regulate powers of police arrest.'],
    headnotes: 'Criminal Procedure - Custodial Deaths and Torture - Fundamental Rights of Arrested Persons - Monetary Compensation.',
  },

  // 14. Lalita Kumari v. Govt. of U.P.
  {
    caseId: 'SC-2014-200',
    caseName: 'Lalita Kumari v. Govt. of U.P.',
    petitioner: 'Lalita Kumari (Minor)',
    respondent: 'Govt. of U.P. and Others',
    court: 'Supreme Court of India',
    decisionDate: '2013-11-12',
    year: 2014,
    citations: ['(2014) 2 SCC 1', 'AIR 2014 SC 187', '2013 INSC 811'],
    normalizedCitations: [],
    docketNumber: 'Writ Petition (Criminal) No. 68 of 2008',
    bench: ['P. Sathasivam, C.J.I.', 'B.S. Chauhan, J.', 'Ranjana P. Desai, J.', 'Ranjan Gogoi, J.', 'S.A. Bobde, J.'],
    docType: 'judgment',
    sourceUrl: 'https://main.sci.gov.in/judgment/judis/41002.pdf',
    isOfficialSource: true,
    chunks: [
      {
        chunkIndex: 0,
        totalChunks: 1,
        text: 'Registration of FIR is mandatory under Section 154 of the Code of Criminal Procedure, if the information discloses commission of a cognizable offence.',
        heading: 'Mandatory Registration of FIR',
        sourceUrl: 'https://main.sci.gov.in/judgment/judis/41002.pdf',
      },
    ],
    keyPassages: ['Registration of FIR is mandatory under Section 154 CrPC if information discloses a cognizable offence.'],
    headnotes: 'Code of Criminal Procedure - Section 154 - Mandatory Registration of First Information Report (FIR).',
  },

  // 15. Arnesh Kumar v. State of Bihar
  {
    caseId: 'SC-2014-8273',
    caseName: 'Arnesh Kumar v. State of Bihar',
    petitioner: 'Arnesh Kumar',
    respondent: 'State of Bihar and Another',
    court: 'Supreme Court of India',
    decisionDate: '2014-07-02',
    year: 2014,
    citations: ['(2014) 8 SCC 273', 'AIR 2014 SC 2756', '2014 INSC 492'],
    normalizedCitations: [],
    docketNumber: 'Criminal Appeal No. 1277 of 2014',
    bench: ['Chandramauli Kr. Prasad, J.', 'Pinaki Chandra Ghose, J.'],
    docType: 'judgment',
    sourceUrl: 'https://main.sci.gov.in/judgment/judis/41736.pdf',
    isOfficialSource: true,
    chunks: [
      {
        chunkIndex: 0,
        totalChunks: 1,
        text: 'No arrest should be made automatically in offences punishable with imprisonment up to 7 years without satisfying conditions under Section 41 CrPC.',
        heading: 'Restrictions on Routine Arrests',
        sourceUrl: 'https://main.sci.gov.in/judgment/judis/41736.pdf',
      },
    ],
    keyPassages: ['Arrest should not be made routinely; notice under Section 41A CrPC must be issued.'],
    headnotes: 'Code of Criminal Procedure - Section 41 and 41A - Section 498A IPC arrests regulated.',
  },

  // 16. Shayara Bano v. Union of India (Triple Talaq)
  {
    caseId: 'SC-2017-9001',
    caseName: 'Shayara Bano v. Union of India',
    petitioner: 'Shayara Bano',
    respondent: 'Union of India and Others',
    court: 'Supreme Court of India',
    decisionDate: '2017-08-22',
    year: 2017,
    citations: ['(2017) 9 SCC 1', 'AIR 2017 SC 4609', '2017 INSC 750'],
    normalizedCitations: [],
    docketNumber: 'Writ Petition (Civil) No. 118 of 2016',
    bench: ['J.S. Khehar, C.J.I.', 'Kurian Joseph, J.', 'R.F. Nariman, J.', 'U.U. Lalit, J.', 'Abdul Nazeer, J.'],
    docType: 'judgment',
    sourceUrl: 'https://main.sci.gov.in/judgment/judis/44990.pdf',
    isOfficialSource: true,
    chunks: [
      {
        chunkIndex: 0,
        totalChunks: 1,
        text: 'The practice of Talaq-e-Biddat (Triple Talaq) is arbitrary and unconstitutional, violative of the fundamental right to equality under Article 14.',
        heading: 'Triple Talaq Struck Down',
        sourceUrl: 'https://main.sci.gov.in/judgment/judis/44990.pdf',
      },
    ],
    keyPassages: ['Triple Talaq (Talaq-e-biddat) is declared void and unconstitutional.'],
    headnotes: 'Muslim Personal Law - Talaq-e-Biddat - Manifest Arbitrariness under Article 14.',
  },

  // 17. Indra Sawhney v. Union of India (Mandal Case)
  {
    caseId: 'SC-1992-3217',
    caseName: 'Indra Sawhney v. Union of India',
    petitioner: 'Indra Sawhney and Others',
    respondent: 'Union of India and Others',
    court: 'Supreme Court of India',
    decisionDate: '1992-11-16',
    year: 1992,
    citations: ['1992 Supp (3) SCC 217', 'AIR 1993 SC 477', '[1992] Supp 2 SCR 454', '1992 INSC 275'],
    normalizedCitations: [],
    docketNumber: 'Writ Petition (Civil) No. 930 of 1990',
    bench: ['M.H. Kania, C.J.I.', 'M.N. Venkatachaliah, J.', 'S. Ratnavel Pandian, J.', 'A.M. Ahmadi, J.', 'B.P. Jeevan Reddy, J.'],
    docType: 'judgment',
    sourceUrl: 'https://main.sci.gov.in/judgment/judis/9950.pdf',
    isOfficialSource: true,
    chunks: [
      {
        chunkIndex: 0,
        totalChunks: 1,
        text: 'Reservation under Article 16(4) is not an exception to Article 16(1) but an instance of classification. The 50 percent ceiling rule must ordinarily be respected.',
        heading: '50 Percent Ceiling and Creamy Layer Doctrine',
        sourceUrl: 'https://main.sci.gov.in/judgment/judis/9950.pdf',
      },
    ],
    keyPassages: ['50% limit on reservations; exclusion of creamy layer among Other Backward Classes (OBCs).'],
    headnotes: 'Constitutional Law - Article 16(4) - OBC Reservations - Creamy Layer Exclusion - 50% Cap.',
  },

  // 18. Christian Medical College Vellore v. Union of India
  {
    caseId: 'SC-1992-1558',
    caseName: 'Christian Medical College Vellore Association v. Union of India',
    petitioner: 'Christian Medical College Vellore Association',
    respondent: 'Union of India and Others',
    court: 'Supreme Court of India',
    decisionDate: '1992-01-15',
    year: 1992,
    citations: ['(1992) 1 SCC 558', '1992 INSC 12'],
    normalizedCitations: [],
    docketNumber: 'Writ Petition (Civil) No. 434 of 1988',
    bench: ['L.M. Sharma, J.', 'M.M. Punchhi, J.'],
    docType: 'judgment',
    sourceUrl: 'https://main.sci.gov.in/judgment/judis/8421.pdf',
    isOfficialSource: true,
    chunks: [
      {
        chunkIndex: 0,
        totalChunks: 1,
        text: 'The fundamental right of minority educational institutions under Article 30 is subject to reasonable regulatory measures promoting academic excellence.',
        heading: 'Minority Rights and Academic Standards',
        sourceUrl: 'https://main.sci.gov.in/judgment/judis/8421.pdf',
      },
    ],
    keyPassages: ['Article 30 rights must balance with state interest in ensuring educational quality and preventing maladministration.'],
    headnotes: 'Education - Minority Educational Institutions - Article 30 - Regulatory Scope.',
  },

  // 19. Whirlpool Corporation v. Registrar of Trade Marks
  {
    caseId: 'SC-1998-8001',
    caseName: 'Whirlpool Corporation v. Registrar of Trade Marks, Mumbai',
    petitioner: 'Whirlpool Corporation',
    respondent: 'Registrar of Trade Marks, Mumbai and Others',
    court: 'Supreme Court of India',
    decisionDate: '1998-10-26',
    year: 1998,
    citations: ['(1998) 8 SCC 1', 'AIR 1999 SC 22', '[1998] Supp 2 SCR 359', '1998 INSC 516'],
    normalizedCitations: [],
    docketNumber: 'Civil Appeal No. 5431 of 1998',
    bench: ['S. Saghir Ahmad, J.', 'B.N. Kirpal, J.'],
    docType: 'judgment',
    sourceUrl: 'https://main.sci.gov.in/judgment/judis/14980.pdf',
    isOfficialSource: true,
    chunks: [
      {
        chunkIndex: 0,
        totalChunks: 1,
        text: 'The alternative remedy does not operate as an absolute bar to writ jurisdiction under Article 226 where fundamental rights are violated, principles of natural justice are breached, or proceedings are wholly without jurisdiction.',
        heading: 'Exceptions to Alternative Remedy Rule under Article 226',
        sourceUrl: 'https://main.sci.gov.in/judgment/judis/14980.pdf',
      },
    ],
    keyPassages: ['High Court can entertain writ petition despite alternative remedy in three specific contingencies.'],
    headnotes: 'Constitution of India - Article 226 - Maintainability of Writ Petition - Alternative Remedy Exception.',
  },

  // 20. S.P. Chengalvaraya Naidu v. Jagannath
  {
    caseId: 'SC-1994-1001',
    caseName: 'S.P. Chengalvaraya Naidu (Dead) by LRs v. Jagannath (Dead) by LRs',
    petitioner: 'S.P. Chengalvaraya Naidu (Dead) by LRs',
    respondent: 'Jagannath (Dead) by LRs and Others',
    court: 'Supreme Court of India',
    decisionDate: '1993-10-27',
    year: 1994,
    citations: ['(1994) 1 SCC 1', 'AIR 1994 SC 853', '[1993] Supp 3 SCR 422', '1993 INSC 440'],
    normalizedCitations: [],
    docketNumber: 'Civil Appeal No. 2211 of 1988',
    bench: ['Kuldip Singh, J.', 'P.B. Sawant, J.'],
    docType: 'judgment',
    sourceUrl: 'https://main.sci.gov.in/judgment/judis/10115.pdf',
    isOfficialSource: true,
    chunks: [
      {
        chunkIndex: 0,
        totalChunks: 1,
        text: 'Fraud avoids all judicial acts, ecclesiastical or temporal. A judgment or decree obtained by playing fraud on the court is a nullity and non-est in the eyes of law.',
        heading: 'Fraud Vitiates Everything Doctrine',
        sourceUrl: 'https://main.sci.gov.in/judgment/judis/10115.pdf',
      },
    ],
    keyPassages: ['Fraud vitiates all judicial acts; a litigant approaching court with unclean hands is entitled to no relief.'],
    headnotes: 'Civil Procedure - Fraud on Court - Suppression of Vital Documents - Decree Obtained by Fraud Nullity.',
  },

  // 21. L. Chandra Kumar v. Union of India
  {
    caseId: 'SC-1997-3261',
    caseName: 'L. Chandra Kumar v. Union of India',
    petitioner: 'L. Chandra Kumar',
    respondent: 'Union of India and Others',
    court: 'Supreme Court of India',
    decisionDate: '1997-03-18',
    year: 1997,
    citations: ['(1997) 3 SCC 261', 'AIR 1997 SC 1125', '[1997] 2 SCR 1186', '1997 INSC 321'],
    normalizedCitations: [],
    docketNumber: 'Civil Appeal No. 481 of 1989',
    bench: ['A.M. Ahmadi, C.J.I.', 'M.M. Punchhi, J.', 'K. Ramaswamy, J.', 'S.P. Bharucha, J.', 'S. Saghir Ahmad, J.', 'K. Venkataswami, J.', 'K.T. Thomas, J.'],
    docType: 'judgment',
    sourceUrl: 'https://main.sci.gov.in/judgment/judis/13210.pdf',
    isOfficialSource: true,
    chunks: [
      {
        chunkIndex: 0,
        totalChunks: 1,
        text: 'The power of judicial review over legislative action vested in the High Courts under Article 226 and in the Supreme Court under Article 32 is an integral and essential feature of the Constitution.',
        heading: 'Tribunals Subject to High Court Writ Jurisdiction',
        sourceUrl: 'https://main.sci.gov.in/judgment/judis/13210.pdf',
      },
    ],
    keyPassages: ['Administrative Tribunals are courts of first instance; decisions are subject to Article 226 scrutiny before Division Bench of High Court.'],
    headnotes: 'Administrative Tribunals Act, 1985 - Exclusion of High Court Jurisdiction Unconstitutional - Basic Structure.',
  },

  // 22. Association for Democratic Reforms (Electoral Bonds)
  {
    caseId: 'SC-2024-113',
    caseName: 'Association for Democratic Reforms v. Union of India',
    petitioner: 'Association for Democratic Reforms and Another',
    respondent: 'Union of India and Others',
    court: 'Supreme Court of India',
    decisionDate: '2024-02-15',
    year: 2024,
    citations: ['(2024) 4 SCC 673', '2024 INSC 113', 'AIR 2024 SC 1234'],
    normalizedCitations: [],
    docketNumber: 'Writ Petition (Civil) No. 880 of 2017',
    bench: ['D.Y. Chandrachud, C.J.I.', 'Sanjiv Khanna, J.', 'B.R. Gavai, J.', 'J.B. Pardiwala, J.', 'Manoj Misra, J.'],
    docType: 'judgment',
    sourceUrl: 'https://main.sci.gov.in/supremecourt/2017/30743/30743_2017_1_1501_50567_Judgement_15-Feb-2024.pdf',
    isOfficialSource: true,
    chunks: [
      {
        chunkIndex: 0,
        totalChunks: 1,
        text: 'The Electoral Bond Scheme is unconstitutional being violative of the right to information under Article 19(1)(a) of the Constitution.',
        heading: 'Electoral Bond Scheme Struck Down',
        sourceUrl: 'https://main.sci.gov.in/supremecourt/2017/30743/30743_2017_1_1501_50567_Judgement_15-Feb-2024.pdf',
      },
    ],
    keyPassages: ['Voters have a fundamental right to know about corporate contributions to political parties under Article 19(1)(a).'],
    headnotes: 'Electoral Bonds - Finance Act 2017 amendments to Companies Act, Income Tax Act, and RPA struck down.',
  },

  // 23. Cox and Kings Ltd v. SAP India Pvt Ltd (Group of Companies)
  {
    caseId: 'SC-2023-1051',
    caseName: 'Cox and Kings Ltd v. SAP India Pvt Ltd',
    petitioner: 'Cox and Kings Ltd',
    respondent: 'SAP India Pvt Ltd and Another',
    court: 'Supreme Court of India',
    decisionDate: '2023-12-06',
    year: 2024,
    citations: ['(2024) 4 SCC 1', '2023 INSC 1051'],
    normalizedCitations: [],
    docketNumber: 'Arbitration Petition No. 38 of 2020',
    bench: ['D.Y. Chandrachud, C.J.I.', 'Hrishikesh Roy, J.', 'P.S. Narasimha, J.', 'J.B. Pardiwala, J.', 'Manoj Misra, J.'],
    docType: 'judgment',
    sourceUrl: 'https://main.sci.gov.in/supremecourt/2020/22194/22194_2020_1_1501_48721_Judgement_06-Dec-2023.pdf',
    isOfficialSource: true,
    chunks: [
      {
        chunkIndex: 0,
        totalChunks: 1,
        text: 'The Group of Companies doctrine is retained in Indian arbitration jurisprudence to bind non-signatory affiliates who actively participated in contract negotiation and performance.',
        heading: 'Group of Companies Doctrine Affirmation',
        sourceUrl: 'https://main.sci.gov.in/supremecourt/2020/22194/22194_2020_1_1501_48721_Judgement_06-Dec-2023.pdf',
      },
    ],
    keyPassages: ['Group of Companies doctrine allows binding non-signatory companies based on mutual intention and corporate nexus.'],
    headnotes: 'Arbitration and Conciliation Act, 1996 - Section 7 - Group of Companies Doctrine - Binding Non-Signatories.',
  },

  // 24. NN Global Mercantile Pvt Ltd v. Indo Unique Flame Ltd
  {
    caseId: 'SC-2023-7001',
    caseName: 'NN Global Mercantile Pvt Ltd v. Indo Unique Flame Ltd',
    petitioner: 'NN Global Mercantile Pvt Ltd',
    respondent: 'Indo Unique Flame Ltd and Others',
    court: 'Supreme Court of India',
    decisionDate: '2023-04-25',
    year: 2023,
    citations: ['(2023) 7 SCC 1', '2023 INSC 420'],
    normalizedCitations: [],
    docketNumber: 'Civil Appeal Nos. 3802-3803 of 2020',
    bench: ['K.M. Joseph, J.', 'Ajay Rastogi, J.', 'Aniruddha Bose, J.', 'Hrishikesh Roy, J.', 'C.T. Ravikumar, J.'],
    docType: 'judgment',
    sourceUrl: 'https://main.sci.gov.in/judgment/judis/46510.pdf',
    isOfficialSource: true,
    chunks: [
      {
        chunkIndex: 0,
        totalChunks: 1,
        text: 'An unstamped or insufficiently stamped arbitration agreement is unenforceable in law until stamped (subsequently reconsidered and clarified by 7-judge bench).',
        heading: 'Arbitration Agreement Stamping',
        sourceUrl: 'https://main.sci.gov.in/judgment/judis/46510.pdf',
      },
    ],
    keyPassages: ['Interplay of Indian Stamp Act and Arbitration Act; initial 5-judge bench decision on non-stamping.'],
    headnotes: 'Arbitration and Conciliation Act, 1996 - Section 11(6) - Stamp Act requirements.',
  },

  // 25. Christian Louboutin SAS v. Nakul Bajaj
  {
    caseId: 'DEL-2018-12215',
    caseName: 'Christian Louboutin SAS v. Nakul Bajaj',
    petitioner: 'Christian Louboutin SAS',
    respondent: 'Nakul Bajaj and Others',
    court: 'High Court of Delhi',
    decisionDate: '2018-11-02',
    year: 2018,
    citations: ['2018 SCC OnLine Del 12215', '2018:DHC:7122'],
    normalizedCitations: [],
    docketNumber: 'CS(COMM) 344 of 2018',
    bench: ['Prathiba M. Singh, J.'],
    docType: 'judgment',
    sourceUrl: 'https://delhihighcourt.nic.in/order-judgments',
    isOfficialSource: true,
    chunks: [
      {
        chunkIndex: 0,
        totalChunks: 1,
        text: 'An e-commerce platform actively promoting, warehousing, or warranting luxury counterfeit goods cannot claim exemption under Section 79 of the Information Technology Act.',
        heading: 'Intermediary Liability and Safe Harbour',
        sourceUrl: 'https://delhihighcourt.nic.in/order-judgments',
      },
    ],
    keyPassages: ['E-commerce platforms lose safe harbour protection when actively involved in counterfeiting.'],
    headnotes: 'Trade Marks Act, 1999 - Section 79 IT Act - E-commerce Intermediary Safe Harbour Dilution.',
  },

  // 26. Godfrey Phillips India Ltd. v. CIT
  {
    caseId: 'BOM-2015-3120',
    caseName: 'Godfrey Phillips India Ltd. v. Commissioner of Income Tax',
    petitioner: 'Godfrey Phillips India Ltd.',
    respondent: 'Commissioner of Income Tax',
    court: 'High Court of Bombay',
    decisionDate: '2015-07-16',
    year: 2015,
    citations: ['(2015) 3 Bom CR 120', '2015:BHC-OS:1450'],
    normalizedCitations: [],
    docketNumber: 'Income Tax Appeal No. 450 of 2013',
    bench: ['Mohit S. Shah, C.J.', 'M.S. Sanklecha, J.'],
    docType: 'judgment',
    sourceUrl: 'https://bombayhighcourt.nic.in',
    isOfficialSource: true,
    chunks: [
      {
        chunkIndex: 0,
        totalChunks: 1,
        text: 'Expenditure incurred purely for sales promotion and commercial expediency is deductible as revenue expenditure under Section 37(1).',
        heading: 'Revenue vs Capital Expenditure',
        sourceUrl: 'https://bombayhighcourt.nic.in',
      },
    ],
    keyPassages: ['Sales promotion expenditure is allowable as business revenue expenditure.'],
    headnotes: 'Income Tax Act, 1961 - Section 37(1) - Revenue vs Capital Expenditure.',
  },

  // 27. Supriyo @ Supriya Chakraborty v. Union of India
  {
    caseId: 'SC-2023-920',
    caseName: 'Supriyo @ Supriya Chakraborty v. Union of India',
    petitioner: 'Supriyo @ Supriya Chakraborty and Another',
    respondent: 'Union of India and Others',
    court: 'Supreme Court of India',
    decisionDate: '2023-10-17',
    year: 2023,
    citations: ['2023 INSC 920', '2023 SCC OnLine SC 1348'],
    normalizedCitations: [],
    docketNumber: 'Writ Petition (Civil) No. 1011 of 2022',
    bench: ['D.Y. Chandrachud, C.J.I.', 'S.K. Kaul, J.', 'S.R. Bhat, J.', 'Hima Kohli, J.', 'P.S. Narasimha, J.'],
    docType: 'judgment',
    sourceUrl: 'https://main.sci.gov.in/supremecourt/2022/36593/36593_2022_1_1501_47614_Judgement_17-Oct-2023.pdf',
    isOfficialSource: true,
    chunks: [
      {
        chunkIndex: 0,
        totalChunks: 1,
        text: 'The Court cannot read gender-neutral language into the Special Marriage Act, 1954; the power to create a legal status of marriage lies within the domain of the legislature.',
        heading: 'Marriage Equality and Special Marriage Act',
        sourceUrl: 'https://main.sci.gov.in/supremecourt/2022/36593/36593_2022_1_1501_47614_Judgement_17-Oct-2023.pdf',
      },
    ],
    keyPassages: ['The right to marry is not an unconditional fundamental right; legislative competence governs marriage enactments.'],
    headnotes: 'Special Marriage Act, 1954 - Same-Sex Marriage - Separation of Powers - Legislative Prerogative.',
  },

  // 28. M.C. Mehta v. Union of India (Oleum Gas Leak)
  {
    caseId: 'SC-1987-1395',
    caseName: 'M.C. Mehta v. Union of India (Oleum Gas Leak)',
    petitioner: 'M.C. Mehta',
    respondent: 'Union of India and Others',
    court: 'Supreme Court of India',
    decisionDate: '1986-12-20',
    year: 1987,
    citations: ['(1987) 1 SCC 395', 'AIR 1987 SC 1086', '[1987] 1 SCR 819', '1986 INSC 280'],
    normalizedCitations: [],
    docketNumber: 'Writ Petition (Civil) No. 12739 of 1985',
    bench: ['P.N. Bhagwati, C.J.I.', 'Ranganath Misra, J.', 'G.L. Oza, J.', 'M.M. Dutt, J.', 'K.N. Singh, J.'],
    docType: 'judgment',
    sourceUrl: 'https://main.sci.gov.in/judgment/judis/7100.pdf',
    isOfficialSource: true,
    chunks: [
      {
        chunkIndex: 0,
        totalChunks: 1,
        text: 'An enterprise engaged in hazardous or inherently dangerous industry owes an absolute and non-delegable duty to ensure that no harm results to anyone. Doctrine of absolute liability formulated.',
        heading: 'Doctrine of Absolute Liability',
        sourceUrl: 'https://main.sci.gov.in/judgment/judis/7100.pdf',
      },
    ],
    keyPassages: ['Absolute liability formulated departing from strict liability in Rylands v. Fletcher without any exceptions.'],
    headnotes: 'Environmental Law - Absolute Liability - Hazardous Industries - Article 32 Compensation.',
  },

  // 29. M.C. Mehta v. Union of India (Taj Trapezium)
  {
    caseId: 'SC-1997-2353',
    caseName: 'M.C. Mehta v. Union of India (Taj Trapezium)',
    petitioner: 'M.C. Mehta',
    respondent: 'Union of India and Others',
    court: 'Supreme Court of India',
    decisionDate: '1996-12-30',
    year: 1997,
    citations: ['(1997) 2 SCC 353', 'AIR 1997 SC 734', '[1996] Supp 10 SCR 704', '1996 INSC 1630'],
    normalizedCitations: [],
    docketNumber: 'Writ Petition (Civil) No. 13381 of 1984',
    bench: ['Kuldip Singh, J.', 'Faizan Uddin, J.'],
    docType: 'judgment',
    sourceUrl: 'https://main.sci.gov.in/judgment/judis/12695.pdf',
    isOfficialSource: true,
    chunks: [
      {
        chunkIndex: 0,
        totalChunks: 1,
        text: 'Precautionary principle and polluter pays principle are part of the environmental law of the country. Industries operating inside Taj Trapezium Zone directed to switch to natural gas or relocate.',
        heading: 'Precautionary Principle and Taj Protection',
        sourceUrl: 'https://main.sci.gov.in/judgment/judis/12695.pdf',
      },
    ],
    keyPassages: ['Precautionary Principle and Polluter Pays Principle are essential components of sustainable development.'],
    headnotes: 'Environmental Law - Taj Mahal Degradation - Taj Trapezium Zone (TTZ) - Precautionary Principle.',
  },

  // 30. National Legal Services Authority (NALSA) v. Union of India
  {
    caseId: 'SC-2014-5438',
    caseName: 'National Legal Services Authority (NALSA) v. Union of India',
    petitioner: 'National Legal Services Authority (NALSA)',
    respondent: 'Union of India and Others',
    court: 'Supreme Court of India',
    decisionDate: '2014-04-15',
    year: 2014,
    citations: ['(2014) 5 SCC 438', 'AIR 2014 SC 1863', '2014 INSC 290'],
    normalizedCitations: [],
    docketNumber: 'Writ Petition (Civil) No. 400 of 2012',
    bench: ['K.S. Radhakrishnan, J.', 'A.K. Sikri, J.'],
    docType: 'judgment',
    sourceUrl: 'https://main.sci.gov.in/judgment/judis/41411.pdf',
    isOfficialSource: true,
    chunks: [
      {
        chunkIndex: 0,
        totalChunks: 1,
        text: 'Transgender persons are recognized as a third gender to safeguard their rights under Part III of the Constitution. Self-determination of gender identity affirmed.',
        heading: 'Recognition of Transgender Rights',
        sourceUrl: 'https://main.sci.gov.in/judgment/judis/41411.pdf',
      },
    ],
    keyPassages: ['Self-determination of gender identity is integral to personal autonomy and dignity under Article 21.'],
    headnotes: 'Constitution of India - Articles 14, 15, 19, 21 - Transgender Persons - Third Gender Recognition.',
  },

  // 31. Anuradha Bhasin v. Union of India
  {
    caseId: 'SC-2020-3637',
    caseName: 'Anuradha Bhasin v. Union of India',
    petitioner: 'Anuradha Bhasin and Ghulam Nabi Azad',
    respondent: 'Union of India and Others',
    court: 'Supreme Court of India',
    decisionDate: '2020-01-10',
    year: 2020,
    citations: ['(2020) 3 SCC 637', 'AIR 2020 SC 1308', '2020 INSC 24'],
    normalizedCitations: [],
    docketNumber: 'Writ Petition (Civil) No. 1031 of 2019',
    bench: ['N.V. Ramana, J.', 'R. Subhash Reddy, J.', 'B.R. Gavai, J.'],
    docType: 'judgment',
    sourceUrl: 'https://main.sci.gov.in/supremecourt/2019/28800/28800_2019_3_1501_19556_Judgement_10-Jan-2020.pdf',
    isOfficialSource: true,
    chunks: [
      {
        chunkIndex: 0,
        totalChunks: 1,
        text: 'Freedom of speech and expression and the right to carry on any profession or business using the medium of internet is constitutionally protected under Article 19(1)(a) and 19(1)(g). Indefinite internet suspensions violate proportionality.',
        heading: 'Internet Access as a Constitutional Medium',
        sourceUrl: 'https://main.sci.gov.in/supremecourt/2019/28800/28800_2019_3_1501_19556_Judgement_10-Jan-2020.pdf',
      },
    ],
    keyPassages: ['Internet suspension orders are subject to judicial review and cannot be imposed indefinitely.'],
    headnotes: 'Telecom Suspension Rules - Internet Shutdowns - Freedom of Speech - Proportionality Standard.',
  },

  // 32. Internet and Mobile Association of India v. RBI (Crypto)
  {
    caseId: 'SC-2020-10274',
    caseName: 'Internet and Mobile Association of India v. Reserve Bank of India',
    petitioner: 'Internet and Mobile Association of India and Others',
    respondent: 'Reserve Bank of India',
    court: 'Supreme Court of India',
    decisionDate: '2020-03-04',
    year: 2020,
    citations: ['(2020) 10 SCC 274', '2020 INSC 263'],
    normalizedCitations: [],
    docketNumber: 'Writ Petition (Civil) No. 506 of 2018',
    bench: ['R.F. Nariman, J.', 'Aniruddha Bose, J.', 'V. Ramasubramanian, J.'],
    docType: 'judgment',
    sourceUrl: 'https://main.sci.gov.in/supremecourt/2018/18260/18260_2018_4_1501_21151_Judgement_04-Mar-2020.pdf',
    isOfficialSource: true,
    chunks: [
      {
        chunkIndex: 0,
        totalChunks: 1,
        text: 'The RBI circular prohibiting banking services to cryptocurrency exchanges was set aside on the ground of proportionality, as RBI failed to show empirical harm to regulated entities.',
        heading: 'Cryptocurrency Banking Ban Struck Down',
        sourceUrl: 'https://main.sci.gov.in/supremecourt/2018/18260/18260_2018_4_1501_21151_Judgement_04-Mar-2020.pdf',
      },
    ],
    keyPassages: ['RBI circular barring crypto exchanges from banking services declared unconstitutional for lack of proportionality.'],
    headnotes: 'Banking Regulation Act, 1949 - RBI Circular on Virtual Currencies - Proportionality Test under Article 19(1)(g).',
  },

  // 33. T.M.A. Pai Foundation v. State of Karnataka
  {
    caseId: 'SC-2002-8481',
    caseName: 'T.M.A. Pai Foundation v. State of Karnataka',
    petitioner: 'T.M.A. Pai Foundation and Others',
    respondent: 'State of Karnataka and Others',
    court: 'Supreme Court of India',
    decisionDate: '2002-10-31',
    year: 2002,
    citations: ['(2002) 8 SCC 481', 'AIR 2003 SC 355', '[2002] Supp 3 SCR 587', '2002 INSC 440'],
    normalizedCitations: [],
    docketNumber: 'Writ Petition (Civil) No. 317 of 1993',
    bench: ['B.N. Kirpal, C.J.I.', 'G.B. Pattanaik, J.', 'V.N. Khare, J.', 'S. Rajendra Babu, J.', 'S.S.M. Quadri, J.'],
    docType: 'judgment',
    sourceUrl: 'https://main.sci.gov.in/judgment/judis/18320.pdf',
    isOfficialSource: true,
    chunks: [
      {
        chunkIndex: 0,
        totalChunks: 1,
        text: 'Private unaided educational institutions enjoy operational autonomy in admissions and fee structure, subject to prohibition of capitation fee and profiteering.',
        heading: 'Private Unaided Institutions Autonomy',
        sourceUrl: 'https://main.sci.gov.in/judgment/judis/18320.pdf',
      },
    ],
    keyPassages: ['Unaided private institutions have constitutional right to establish and administer schools and colleges under Article 19(1)(g).'],
    headnotes: 'Constitution of India - Article 30 and Article 19(1)(g) - Private Unaided Educational Institutions.',
  },

  // 34. Kihoto Hollohan v. Zachillhu (Anti-Defection Law)
  {
    caseId: 'SC-1992-651',
    caseName: 'Kihoto Hollohan v. Zachillhu',
    petitioner: 'Kihoto Hollohan',
    respondent: 'Zachillhu and Others',
    court: 'Supreme Court of India',
    decisionDate: '1992-02-18',
    year: 1992,
    citations: ['1992 Supp (2) SCC 651', 'AIR 1993 SC 412', '[1992] 1 SCR 686', '1992 INSC 50'],
    normalizedCitations: [],
    docketNumber: 'Transfer Case (Civil) No. 40 of 1991',
    bench: ['L.M. Sharma, J.', 'M.N. Venkatachaliah, J.', 'J.S. Verma, J.', 'K. Jayachandra Reddy, J.', 'S.C. Agrawal, J.'],
    docType: 'judgment',
    sourceUrl: 'https://main.sci.gov.in/judgment/judis/9123.pdf',
    isOfficialSource: true,
    chunks: [
      {
        chunkIndex: 0,
        totalChunks: 1,
        text: 'The Speaker while adjudicating disqualification petitions under the Tenth Schedule acts as a Tribunal, and orders are subject to judicial review under Articles 136 and 226.',
        heading: 'Tenth Schedule Judicial Review',
        sourceUrl: 'https://main.sci.gov.in/judgment/judis/9123.pdf',
      },
    ],
    keyPassages: ['Decisions of the Speaker/Chairman under the Tenth Schedule are subject to judicial review.'],
    headnotes: 'Constitution of India - Tenth Schedule - Anti-Defection Law - Paragraph 7 held invalid; Paragraph 6 justiciable.',
  },

  // 35. State of Haryana v. Bhajan Lal
  {
    caseId: 'SC-1992-335',
    caseName: 'State of Haryana v. Bhajan Lal',
    petitioner: 'State of Haryana and Others',
    respondent: 'Bhajan Lal and Others',
    court: 'Supreme Court of India',
    decisionDate: '1990-11-21',
    year: 1992,
    citations: ['1992 Supp (1) SCC 335', 'AIR 1992 SC 604', '[1990] Supp 3 SCR 259', '1990 INSC 363'],
    normalizedCitations: [],
    docketNumber: 'Civil Appeal No. 5412 of 1990',
    bench: ['S. Ratnavel Pandian, J.', 'K. Jayachandra Reddy, J.'],
    docType: 'judgment',
    sourceUrl: 'https://main.sci.gov.in/judgment/judis/8890.pdf',
    isOfficialSource: true,
    chunks: [
      {
        chunkIndex: 0,
        totalChunks: 1,
        text: 'The High Court can quash criminal proceedings or FIR under Section 482 CrPC only in exceptional cases falling within the seven enunciated categories.',
        heading: 'Seven Guidelines for Quashing FIR under Section 482',
        sourceUrl: 'https://main.sci.gov.in/judgment/judis/8890.pdf',
      },
    ],
    keyPassages: ['Seven illustrative categories where High Court can quash FIR under Section 482 CrPC or Article 226.'],
    headnotes: 'Code of Criminal Procedure - Section 482 - Quashing of First Information Report and Criminal Proceedings.',
  },

  // 36. Selvi v. State of Karnataka
  {
    caseId: 'SC-2010-7263',
    caseName: 'Selvi v. State of Karnataka',
    petitioner: 'Selvi and Others',
    respondent: 'State of Karnataka',
    court: 'Supreme Court of India',
    decisionDate: '2010-05-05',
    year: 2010,
    citations: ['(2010) 7 SCC 263', 'AIR 2010 SC 1974', '2010 INSC 319'],
    normalizedCitations: [],
    docketNumber: 'Criminal Appeal No. 1267 of 2004',
    bench: ['K.G. Balakrishnan, C.J.I.', 'R.V. Raveendran, J.', 'J.M. Panchal, J.'],
    docType: 'judgment',
    sourceUrl: 'https://main.sci.gov.in/judgment/judis/36340.pdf',
    isOfficialSource: true,
    chunks: [
      {
        chunkIndex: 0,
        totalChunks: 1,
        text: 'Involuntary administration of narcoanalysis, polygraph examination, and brain electrical activation profile (BEAP) tests violates the right against self-incrimination under Article 20(3) and personal liberty under Article 21.',
        heading: 'Involuntary Neuro-Scientific Tests Violate Article 20(3)',
        sourceUrl: 'https://main.sci.gov.in/judgment/judis/36340.pdf',
      },
    ],
    keyPassages: ['Forcible administration of narcoanalysis or lie-detector tests is unconstitutional and infringes mental privacy.'],
    headnotes: 'Constitutional Law - Article 20(3) and Article 21 - Narcoanalysis - Brain Mapping - Right to Silence.',
  },

  // 37. Jacob Mathew v. State of Punjab
  {
    caseId: 'SC-2005-6001',
    caseName: 'Jacob Mathew v. State of Punjab',
    petitioner: 'Dr. Jacob Mathew',
    respondent: 'State of Punjab and Another',
    court: 'Supreme Court of India',
    decisionDate: '2005-08-05',
    year: 2005,
    citations: ['(2005) 6 SCC 1', 'AIR 2005 SC 3180', '2005 INSC 377'],
    normalizedCitations: [],
    docketNumber: 'Criminal Appeal Nos. 144-145 of 2004',
    bench: ['R.C. Lahoti, C.J.I.', 'G.P. Mathur, J.', 'P.K. Balasubramanyan, J.'],
    docType: 'judgment',
    sourceUrl: 'https://main.sci.gov.in/judgment/judis/27122.pdf',
    isOfficialSource: true,
    chunks: [
      {
        chunkIndex: 0,
        totalChunks: 1,
        text: 'A simple lack of care or an error of judgment does not constitute criminal medical negligence under Section 304A IPC; gross negligence is mandatory.',
        heading: 'Standard of Criminal Medical Negligence',
        sourceUrl: 'https://main.sci.gov.in/judgment/judis/27122.pdf',
      },
    ],
    keyPassages: ['A medical practitioner cannot be prosecuted under Section 304A IPC unless gross negligence or recklessness is established by medical opinion.'],
    headnotes: 'Indian Penal Code - Section 304A - Medical Negligence - Guidelines to prevent doctor harassment.',
  },

  // 38. Bachan Singh v. State of Punjab (Death Penalty)
  {
    caseId: 'SC-1980-2684',
    caseName: 'Bachan Singh v. State of Punjab',
    petitioner: 'Bachan Singh',
    respondent: 'State of Punjab',
    court: 'Supreme Court of India',
    decisionDate: '1980-05-09',
    year: 1980,
    citations: ['(1980) 2 SCC 684', 'AIR 1980 SC 898', '[1980] 2 SCR 645', '1980 INSC 96'],
    normalizedCitations: [],
    docketNumber: 'Criminal Appeal No. 273 of 1979',
    bench: ['Y.V. Chandrachud, C.J.I.', 'A. Gupta, J.', 'N.L. Untwalia, J.', 'P.S. Kailasam, J.', 'P.N. Bhagwati, J.'],
    docType: 'judgment',
    sourceUrl: 'https://main.sci.gov.in/judgment/judis/5390.pdf',
    isOfficialSource: true,
    chunks: [
      {
        chunkIndex: 0,
        totalChunks: 1,
        text: 'The death penalty under Section 302 IPC is constitutional, but must be awarded only in the rarest of rare cases when the alternative option of life imprisonment is unquestionably foreclosed.',
        heading: 'Rarest of Rare Cases Doctrine',
        sourceUrl: 'https://main.sci.gov.in/judgment/judis/5390.pdf',
      },
    ],
    keyPassages: ['Death penalty should be awarded only in the rarest of rare cases after weighing aggravating and mitigating factors.'],
    headnotes: 'Indian Penal Code - Section 302 - Constitutionality of Capital Punishment - Rarest of Rare doctrine.',
  },

  // 39. Mohd. Ahmed Khan v. Shah Bano Begum
  {
    caseId: 'SC-1985-2556',
    caseName: 'Mohd. Ahmed Khan v. Shah Bano Begum',
    petitioner: 'Mohd. Ahmed Khan',
    respondent: 'Shah Bano Begum and Others',
    court: 'Supreme Court of India',
    decisionDate: '1985-04-23',
    year: 1985,
    citations: ['(1985) 2 SCC 556', 'AIR 1985 SC 945', '[1985] 3 SCR 844', '1985 INSC 98'],
    normalizedCitations: [],
    docketNumber: 'Criminal Appeal No. 103 of 1981',
    bench: ['Y.V. Chandrachud, C.J.I.', 'D.A. Desai, J.', 'O. Chinnappa Reddy, J.', 'E.S. Venkataramiah, J.', 'Ranganath Misra, J.'],
    docType: 'judgment',
    sourceUrl: 'https://main.sci.gov.in/judgment/judis/6401.pdf',
    isOfficialSource: true,
    chunks: [
      {
        chunkIndex: 0,
        totalChunks: 1,
        text: 'Section 125 of the Code of Criminal Procedure applies to all citizens irrespective of religion. A divorced Muslim woman unable to maintain herself is entitled to maintenance beyond Iddat period until remarriage.',
        heading: 'Secular Scope of Maintenance under Section 125 CrPC',
        sourceUrl: 'https://main.sci.gov.in/judgment/judis/6401.pdf',
      },
    ],
    keyPassages: ['Section 125 CrPC cuts across personal laws to prevent vagrancy and destitution.'],
    headnotes: 'Code of Criminal Procedure - Section 125 - Maintenance of Divorced Muslim Wife - Religion Neutral.',
  },

  // 40. Indian Young Lawyers Assn v. State of Kerala (Sabarimala)
  {
    caseId: 'SC-2019-11001',
    caseName: 'Indian Young Lawyers Association v. State of Kerala',
    petitioner: 'Indian Young Lawyers Association and Others',
    respondent: 'State of Kerala and Others',
    court: 'Supreme Court of India',
    decisionDate: '2018-09-28',
    year: 2019,
    citations: ['(2019) 11 SCC 1', 'AIR 2018 SC 5670', '2018 INSC 895'],
    normalizedCitations: [],
    docketNumber: 'Writ Petition (Civil) No. 373 of 2006',
    bench: ['Dipak Misra, C.J.I.', 'R.F. Nariman, J.', 'A.M. Khanwilkar, J.', 'D.Y. Chandrachud, J.', 'Indu Malhotra, J.'],
    docType: 'judgment',
    sourceUrl: 'https://main.sci.gov.in/supremecourt/2006/18956/18956_2006_Judgement_28-Sep-2018.pdf',
    isOfficialSource: true,
    chunks: [
      {
        chunkIndex: 0,
        totalChunks: 1,
        text: 'Exclusion of women of menstruating age from Sabarimala temple violates constitutional morality, freedom of religion under Article 25, and right to equality under Article 14.',
        heading: 'Sabarimala Temple Entry Affirmation',
        sourceUrl: 'https://main.sci.gov.in/supremecourt/2006/18956/18956_2006_Judgement_28-Sep-2018.pdf',
      },
    ],
    keyPassages: ['Devotion cannot be subjected to physiological attributes; Rule 3(b) of Kerala Hindu Places of Public Worship Rules declared unconstitutional.'],
    headnotes: 'Constitution of India - Articles 14, 15, 25, 26 - Sabarimala Entry - Freedom of Conscience.',
  },
];
